trigger: none

# resources:
#   repositories:
#     - repository: DevOps
#       type: git
#       name: 'Viewfinder Common/DevOps'
#       ref: refs/heads/develop

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'#'Release'
  serviceConnection: 'CS Watchdog Approval Flow Connection'
  serviceConnectionExternal: 'watchdog_external'

jobs: 
- job: Invoke_CS_Watchdog
  pool: server
  continueOnError: true
  steps:
  - task: InvokeRESTAPI@1
    displayName: 'Get Approval'
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'CS Watchdog Approval Flow Connection'
      method: 'POST'
      headers: "{'Content-Type':'application/json',  'AuthToken': '$(system.AccessToken)', 'runKey': 'EF46E8B9A759417468DBC7EB72433'}" 
      body: |
         {
            "buildNumber": "$(build.buildId)",
            "isMultiBranch": "true",
            "branchName": "$(build.sourceBranchName)",
            "PlanUrl": "$(system.CollectionUri)",
            "ProjectId": "$(system.TeamProjectId)",
            "HubName": "$(system.HostType)",
            "PlanId": "$(system.PlanId)",
            "JobId": "$(system.JobId)",
            "TimelineId": "$(system.TimelineId)",
            "TaskInstanceId": "$(system.TaskInstanceId)",
            "QueuedBy": "$(build.QueuedBy)",
            "buildConfiguration": "$(buildConfiguration)",
            "buildPlatform": "$(buildPlatform)",
            "solution": "$(solution)"
         }
      urlSuffix: "&sig=4g28FDXHg0gUsEeTQgMuf9Hw3jyWwkVEgL80TWU4Xos"
      waitForCompletion: 'true'
      # successCriteria: eq(root['status'], 'successful')

- job: Retrieve_Variables_From_Key_Vault
  pool:
    Default
  continueOnError: true
  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: $(serviceConnectionExternal)
      KeyVaultName: 'cswatchdog-external-kv'
      SecretsFilter: 'cs-watchdog-flow-access-token'
    displayName: 'Get key vault secrets as pipeline variables'
  - task: CmdLine@2
    displayName: Use Secret Values
    inputs:
      script: |
        echo $cs-watchdog-flow-access-token
        echo $(cs-watchdog-flow-access-token)
        echo ${cs-watchdog-flow-access-token}
